@url = http://localhost:5000
@reservationID = 1;

###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{reservationID}}

###
POST {{url}}/reservations
Content-Type: application/json

{
  "EmploteeName": "John Doe",
  "ParkingSpotName": "P2",
  "LicensePlate": "PL2137"
}

###
PUT {{url}}/reservations/{{reservationID}}
Content-Type: application/json

{
  "licensePlate": "XYZ123"
}

###
DELETE {{url}}/reservations/{{reservationID}}