@url = http://localhost:5000

###
GET {{url}}/reservations

###
POST {{url}}/reservations
Content-Type: application/json

{
  "EmploteeName": "John Doe",
  "ParkingSpotName": "P0",
  "LicensePlate": "PL2137"
}
