@url = http://localhost:5000/
@reservationID = 1
@parkingSpotId = "00-4381b1043919a3fa96e0c463ad94afa1-3532a5cc0d70b51d-00"

###
GET {{url}}

###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{reservationID}}

###
POST {{url}}/reservations
Content-Type: application/json

{
  "parkingSpotId": {{parkingSpotId}},
  "employeeName": "Maciej",
  "licensePlate": "XYZ123",
  "date": "2024-08-14"
}

###
PUT {{url}}/reservations/{{reservationID}}
Content-Type: application/json

{
  "licensePlate": "XYZ123"
}

###
DELETE {{url}}/reservations/{{reservationID}}