GET http://localhost:5209/todos

###

POST http://localhost:5209/todos
Content-Type: application/json

{
"Id": 1,
"Name": "demo 1",
"DueDate": "2024-12-30",
"IsComplited": false
}

###

GET http://localhost:5209/todos/2

###

DELETE http://localhost:5209/todos/1

###

GET http://localhost:5209/task/2