@url = http://localhost:5000

Accept: application/json

###

 GET {{url}}
 
###
 
 GET {{url}}/ReservationsControllers
 
###
 
 POST {{url}}/ReservationsControllers
 Content-Type: application/json
 
###
 
 PUT {{url}}/reservations